SK_CRM/SK_CRM/Models/EmployeeMenu.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SK_CRM.Models
{
    public class EmployeeMenu
    {
        [Key]
        [Display(Name = "Menu Id")]
        public long MenuId { get; set; }

        [Required]
        [Display(Name = "Menu Name")]
        public string MenuName { get; set; }

        [Display(Name = "Main Menu")]
        public long? MainMenuId { get; set; }

        [Display(Name = "URL Path")]
        public string URLPath { get; set; }

        [Required]
        [Display(Name = "Order By")]
        public long OrderBy { get; set; }

        [Display(Name = "Is NotActive")]
        public bool IsNotActive { get; set; }

        [Display(Name = "NotActive Date")]
        public DateTime? NotActiveDate { get; set; }

        [Display(Name = "Created Date")]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "Modified Date")]
        public DateTime ModifiedDate { get; set; }

        [Display(Name = "Is Deleted")]
        public bool IsDeleted { get; set; }

        [Display(Name = "Deleted Date")]
        public DateTime? DeletedDate { get; set; }

        [Display(Name = "Font Icon")]
        public string FontIcon { get; set; }

        [Display(Name = "Created By")]
        public string CreatedBy { get; set; }

        [Display(Name = "Modified By")]
        public string ModifiedBy { get; set; }

        [Display(Name = "DeletedBy")]
        public string DeletedBy { get; set; }
    }

    public class EmployeeMenuGrid
    {
        [Display(Name = "Menu Id")]
        public long MenuId { get; set; }

        [Display(Name = "Menu Name")]
        public string MenuName { get; set; }

        [Display(Name = "Main Menu")]
        public string MainMenu { get; set; }

        [Display(Name = "URL Path")]
        public string URLPath { get; set; }

        [Display(Name = "Order By")]
        public long OrderBy { get; set; }

        [Display(Name = "Is NotActive")]
        public bool IsNotActive { get; set; }

        [Display(Name = "NotActive Date")]
        public DateTime? NotActiveDate { get; set; }

        [Display(Name = "Created Date")]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "Modified Date")]
        public DateTime ModifiedDate { get; set; }

        [Display(Name = "Is Deleted")]
        public bool IsDeleted { get; set; }

        [Display(Name = "Font Icon")]
        public string FontIcon { get; set; }
    }

    public class AllEmployeeMenuModel
    {
        public List<EmployeeMenu> employeeMenus { get; set; }

        public int currentPage { get; set; }
        public int pageSize { get; set; }
        public int totalCount { get; set; }

        public int skipCount { get; set; }
        public int pagefirstNumber { get; set; }
        public int pageLastNumber { get; set; }

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(totalCount, pageSize));

        public bool ShowPrevious => currentPage > 1;
        public bool ShowNext => currentPage < TotalPages;

        public int MinPage => currentPage - 5 > 0 ? currentPage - 5 : 1;

        public int MaxPage => MinPage + 9 < TotalPages ? MinPage + 9 : TotalPages;
    }

    public class AllRolesModel
    {
        public List<IdentityRole> roles { get; set; }

        public int currentPage { get; set; }
        public int pageSize { get; set; }
        public int totalCount { get; set; }

        public int skipCount { get; set; }
        public int pagefirstNumber { get; set; }
        public int pageLastNumber { get; set; }

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(totalCount, pageSize));

        public bool ShowPrevious => currentPage > 1;
        public bool ShowNext => currentPage < TotalPages;

        public int MinPage => currentPage - 5 > 0 ? currentPage - 5 : 1;

        public int MaxPage => MinPage + 9 < TotalPages ? MinPage + 9 : TotalPages;
    }

    public class UserwithRole
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public string PhoneNumber { get; set; }
    }

    public class AllUsersModel
    {
        public List<UserwithRole> users { get; set; }
        public List<IdentityRole> roles { get; set; }

        public int currentPage { get; set; }
        public int pageSize { get; set; }
        public int totalCount { get; set; }

        public int skipCount { get; set; }
        public int pagefirstNumber { get; set; }
        public int pageLastNumber { get; set; }

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(totalCount, pageSize));

        public bool ShowPrevious => currentPage > 1;
        public bool ShowNext => currentPage < TotalPages;

        public int MinPage => currentPage - 5 > 0 ? currentPage - 5 : 1;

        public int MaxPage => MinPage + 9 < TotalPages ? MinPage + 9 : TotalPages;
    }
}

SK_CRM/SK_CRM/Controllers/EmployeeMenusController.cs
using Microsoft.AspNet.Identity;
using SK_CRM.Models;
using SK_CRM.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SK_CRM.Controllers
{
    [Authorize]
    public class EmployeeMenusController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        private readonly CommonServices _commonServices = new CommonServices();

        // GET: EmployeeMenus
        public async Task<ActionResult> Index()
        {
            try
            {
                //long MenuId = 37;
                //string UserID = User.Identity.GetUserId();
                //UserID = UserID ?? "";

                //if (!_commonServices.CheckUserMenuPermission(MenuId, UserID))
                //{
                //    return RedirectToAction("Index", "ErrorHandler");
                //}
                //ViewBag.RBSPersmission = _commonServices.GetMenuPermission(MenuId, UserID);
                //SqlParameter[] param = { };
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult _PartialGetAllEmployeeMenus(int currentpage = 1, int pagesize = 10)
        {
            int totalcount = db.EmployeeMenus.Where(x => x.IsDeleted == false).Select(p => p.MenuId).Count();
            int skipcount = (currentpage - 1) * pagesize;
            AllEmployeeMenuModel companysModel = new AllEmployeeMenuModel()
            {
                employeeMenus = db.EmployeeMenus.Where(x => x.IsDeleted == false).OrderBy(x => x.MenuId).Skip(skipcount).Take(pagesize).ToList(),
                currentPage = currentpage,
                pageSize = pagesize,
                totalCount = totalcount,
                skipCount = skipcount,
                pagefirstNumber = totalcount > skipcount ? skipcount + 1 : totalcount,
                pageLastNumber = totalcount > skipcount + pagesize ? skipcount + pagesize : totalcount
            };
            return PartialView(companysModel);
        }

        // GET: EmployeeMenus/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                EmployeeMenu employeeMenu = await db.EmployeeMenus.FindAsync(id);
                if (employeeMenu == null)
                {
                    return HttpNotFound();
                }
                return View(employeeMenu);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: EmployeeMenus/Create
        public ActionResult Create()
        {
            try
            {
                string UserID = User.Identity.GetUserId();
                UserID = UserID ?? "";

                if (!_commonServices.CheckUserMenuPermission(38, UserID))
                {
                    return RedirectToAction("Index", "ErrorHandler");
                }

                ViewBag.MainMenus = db.EmployeeMenus.Where(obj => obj.IsDeleted == false && obj.IsNotActive == false && obj.MainMenuId == null).OrderBy(obj => obj.MenuName).ToList();
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: EmployeeMenus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "MenuId,MenuName,MainMenuId,URLPath,OrderBy,IsNotActive,FontIcon")] EmployeeMenu employeeMenu)
        {
            try
            {
                long orderby = 1;
                if (await db.EmployeeMenus.CountAsync() > 0)
                {
                    orderby = await db.EmployeeMenus.MaxAsync(item => item.OrderBy) + 1;
                }
                if (employeeMenu.IsNotActive)
                {
                    employeeMenu.NotActiveDate = DateTime.Now;
                }
                ModelState["OrderBy"].Errors.Clear();
                employeeMenu.OrderBy = orderby;
                employeeMenu.CreatedDate = DateTime.Now;
                employeeMenu.ModifiedDate = DateTime.Now;

                string UserID = User.Identity.GetUserId();
                employeeMenu.CreatedBy = UserID;
                employeeMenu.ModifiedBy = UserID;
                if (ModelState.IsValid)
                {
                    db.EmployeeMenus.Add(employeeMenu);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                ViewBag.MainMenus = db.EmployeeMenus.Where(obj => obj.IsDeleted == false && obj.IsNotActive == false && obj.MainMenuId == null).OrderBy(obj => obj.MenuName).ToList();
                return View(employeeMenu);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: EmployeeMenus/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                EmployeeMenu employeeMenu = await db.EmployeeMenus.FindAsync(id);
                if (employeeMenu == null)
                {
                    return HttpNotFound();
                }
                ViewBag.MainMenus = db.EmployeeMenus.Where(obj => obj.IsDeleted == false && obj.IsNotActive == false && obj.MainMenuId == null).OrderBy(obj => obj.MenuName).ToList();
                return View(employeeMenu);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: EmployeeMenus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "MenuId,MenuName,MainMenuId,URLPath,OrderBy,IsNotActive,FontIcon")] EmployeeMenu employeeMenu)
        {
            try
            {
                EmployeeMenu employeeMenu1 = await db.EmployeeMenus.FindAsync(employeeMenu.MenuId);
                employeeMenu1.ModifiedDate = DateTime.Now;
                employeeMenu1.MenuName = employeeMenu.MenuName;
                employeeMenu1.MainMenuId = employeeMenu.MainMenuId;
                employeeMenu1.URLPath = employeeMenu.URLPath;
                employeeMenu1.OrderBy = employeeMenu.OrderBy;
                employeeMenu1.IsNotActive = employeeMenu.IsNotActive;
                employeeMenu1.FontIcon = employeeMenu.FontIcon;

                if (employeeMenu.IsNotActive)
                {
                    employeeMenu1.NotActiveDate = DateTime.Now;
                }

                string UserID = User.Identity.GetUserId();
                employeeMenu1.ModifiedBy = UserID;
                if (ModelState.IsValid)
                {
                    db.Entry(employeeMenu1).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }

                ViewBag.MainMenus = db.EmployeeMenus.Where(obj => obj.IsDeleted == false && obj.IsNotActive == false && obj.MainMenuId == null).OrderBy(obj => obj.MenuName).ToList();
                return View(employeeMenu);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: EmployeeMenus/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeMenu employeeMenu = await db.EmployeeMenus.FindAsync(id);
            if (employeeMenu == null)
            {
                return HttpNotFound();
            }
            return View(employeeMenu);
        }

        // POST: EmployeeMenus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            EmployeeMenu employeeMenu = await db.EmployeeMenus.FindAsync(id);
            employeeMenu.DeletedDate = DateTime.Now;

            string UserID = User.Identity.GetUserId();
            employeeMenu.DeletedBy = UserID;
            employeeMenu.IsDeleted = true;
            if (ModelState.IsValid)
            {
                db.Entry(employeeMenu).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SK_CRM/SK_CRM/Views/EmployeeMenus/Create.cshtml
@model SK_CRM.Models.EmployeeMenu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}

<div class="content-wrapper container-xxl p-0">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <!-- Horizontal Wizard -->
        <section class="horizontal-wizard">
            <div class="bs-stepper horizontal-wizard-example">
                <div class="bs-stepper-header" role="tablist">
                    <div class="step active" data-target="#account-details" role="tab" id="account-details-trigger">
                        <button type="button" class="step-trigger">
                            <span class="bs-stepper-box">1</span>
                            <span class="bs-stepper-label">
                                <span class="bs-stepper-title">Role Details</span>
                                <span class="bs-stepper-subtitle">Setup Role Details</span>
                            </span>
                        </button>
                    </div>
                    <div class="line">
                        <i data-feather="chevron-right" class="font-medium-2"></i>
                    </div>


                </div>
                <div class="bs-stepper-content">

                    <div id="account-details" class="content active dstepper-block" role="tabpanel" aria-labelledby="account-details-trigger">
                        <div class="content-header">
                            <h5 class="mb-0">Employee Menu Details</h5>
                            <small class="text-muted">Enter New Employee Menu Details.</small>
                        </div>
                        @using (Html.BeginForm("Create", "EmployeeMenus", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.MenuId)
                            <div class="row">
                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.MenuName, htmlAttributes: new { @class = "form-label" })
                                    @Html.EditorFor(model => model.MenuName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Role Name" } })
                                    @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                                </div>

                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.MainMenuId, htmlAttributes: new { @class = "form-label" })
                                    @Html.DropDownListFor(m => m.MainMenuId,
                                             new SelectList(ViewBag.MainMenus, "MenuId", "MenuName"), "Select MainMenu", new { @class = "form-control input-height" })
                                    @Html.ValidationMessageFor(model => model.MainMenuId, "", new { @class = "text-danger" })
                                </div>

                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.URLPath, htmlAttributes: new { @class = "form-label" })
                                    @Html.EditorFor(model => model.URLPath, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Role Name" } })
                                    @Html.ValidationMessageFor(model => model.URLPath, "", new { @class = "text-danger" })
                                </div>
                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.OrderBy, htmlAttributes: new { @class = "form-label" })
                                    @Html.EditorFor(model => model.OrderBy, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Role Name" } })
                                    @Html.ValidationMessageFor(model => model.OrderBy, "", new { @class = "text-danger" })
                                </div>

                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.IsNotActive, htmlAttributes: new { @class = "form-label" })
                                    @Html.EditorFor(model => model.IsNotActive)
                                    @Html.ValidationMessageFor(model => model.IsNotActive, "", new { @class = "text-danger" })
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.FontIcon, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.FontIcon, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.FontIcon, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                            </div>
                            <div class="d-flex justify-content-between">

                                <button class="btn btn-success" type="submit" id="btnCompanySave"><i class="fa fa-spinner fa-spin hide-spinner"></i>Submit</button>
                            </div>
                        }

                    </div>



                    @*}*@
                </div>

            </div>
        </section>
        <!-- /Horizontal Wizard -->
    </div>

</div>

SK_CRM/SK_CRM/Views/EmployeeMenus/Edit.cshtml
@model SK_CRM.Models.EmployeeMenu

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}

<div class="content-wrapper container-xxl p-0">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <!-- Horizontal Wizard -->
        <section class="horizontal-wizard">
            <div class="bs-stepper horizontal-wizard-example">
                <div class="bs-stepper-header" role="tablist">
                    <div class="step active" data-target="#account-details" role="tab" id="account-details-trigger">
                        <button type="button" class="step-trigger">
                            <span class="bs-stepper-box">1</span>
                            <span class="bs-stepper-label">
                                <span class="bs-stepper-title">Employee Menu Details</span>
                                <span class="bs-stepper-subtitle">Setup Employee Menu Details</span>
                            </span>
                        </button>
                    </div>
                    <div class="line">
                        <i data-feather="chevron-right" class="font-medium-2"></i>
                    </div>


                </div>
                <div class="bs-stepper-content">

                    <div id="account-details" class="content active dstepper-block" role="tabpanel" aria-labelledby="account-details-trigger">
                        <div class="content-header">
                            <h5 class="mb-0">Employee Menu Details</h5>
                            <small class="text-muted">Edit Employee Menu Details.</small>
                        </div>
                        @using (Html.BeginForm("Edit", "EmployeeMenus", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.MenuId)
                            <div class="row">
                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.MenuName, htmlAttributes: new { @class = "form-label" })
                                    @Html.EditorFor(model => model.MenuName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Role Name" } })
                                    @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                                </div>

                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.MainMenuId, htmlAttributes: new { @class = "form-label" })
                                    @Html.DropDownListFor(m => m.MainMenuId,
                                             new SelectList(ViewBag.MainMenus, "MenuId", "MenuName"), "Select MainMenu", new { @class = "form-control input-height" })
                                    @Html.ValidationMessageFor(model => model.MainMenuId, "", new { @class = "text-danger" })
                                </div>

                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.URLPath, htmlAttributes: new { @class = "form-label" })
                                    @Html.EditorFor(model => model.URLPath, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Role Name" } })
                                    @Html.ValidationMessageFor(model => model.URLPath, "", new { @class = "text-danger" })
                                </div>
                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.OrderBy, htmlAttributes: new { @class = "form-label" })
                                    @Html.EditorFor(model => model.OrderBy, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Role Name" } })
                                    @Html.ValidationMessageFor(model => model.OrderBy, "", new { @class = "text-danger" })
                                </div>

                                <div class="mb-1 col-md-6">
                                    @Html.LabelFor(model => model.IsNotActive, htmlAttributes: new { @class = "form-label" })
                                    @Html.EditorFor(model => model.IsNotActive)
                                    @Html.ValidationMessageFor(model => model.IsNotActive, "", new { @class = "text-danger" })
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.FontIcon, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.FontIcon, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.FontIcon, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                            </div>
                            <div class="d-flex justify-content-between">

                                <button class="btn btn-success" type="submit" id="btnCompanySave"><i class="fa fa-spinner fa-spin hide-spinner"></i>Submit</button>
                            </div>
                        }

                    </div>



                    @*}*@
                </div>

            </div>
        </section>
        <!-- /Horizontal Wizard -->
    </div>

</div>

SK_CRM/SK_CRM/Views/EmployeeMenus/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}

@{
    Html.RenderAction("_PartialGetAllEmployeeMenus", "EmployeeMenus");
}