SK_CRM/SK_CRM/Models/Quotation.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SK_CRM.Models
{
    [Table("SK.QuotationDetails", Schema = "dbo")]
    public class Quotation
    {
        [Key]
        [Display(Name = "Id")]
        public int QuotationId { get; set; }
        [Required]
        [Display(Name = "Quot. No")]
        public string QuotationNo { get; set; }
        [Required]
        [Display(Name = "Date")]
        public DateTime QuotationDate { get; set; }
        [Required]
        [Display(Name = "Due Date")]
        public DateTime QuotationDueDate { get; set; }
        [Required]
        [Display(Name = "Billed By")]
        public int BilledByCompanyId { get; set; }
        [Required]
        [Display(Name = "Billed To")]
        public int BilledToCustomerId { get; set; }
        [Display(Name = "Ref. Person")]
        public int? RefPersonId { get; set; }

        public DateTime CreateDate { get; set; }
        public DateTime ModifiedDate { get; set; }

        public string QuotationPath { get; set; }
    }
}

SK_CRM/SK_CRM/Controllers/quotationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SK_CRM.Models;
using System.Data.SqlClient;
using SK_CRM.Models.AggregateModel;
using System.IO;
using OpenHtmlToPdf;
using SK_CRM.Services;
using System.Diagnostics;
using Spire.Doc.Fields;
using Spire.Doc.Documents;
using Spire.Doc;
//using Create_WordPDF;
using WordToPDF;

namespace SK_CRM.Controllers
{
    [Authorize]
    public class quotationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //private Cls_WordPDF clsWordPDF { get; set; } = new Cls_WordPDF();
        private readonly CommonServices _services = new CommonServices();
        private long MenuID;
        // GET: quotations
        public async Task<ActionResult> Index()
        {
            MenuID = 8;
            EmployeeMenu menu = _services.GetEmployeeMenuByID(MenuID);
            ViewBag.Menu = menu.MenuName;
            return View(await db.Quotations.ToListAsync());
        }

        // GET: quotations/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotation quotation = await db.Quotations.FindAsync(id);
            if (quotation == null)
            {
                return HttpNotFound();
            }
            return View(quotation);
        }

        // GET: quotations/Details/5
        public async Task<ActionResult> preview(int? id)
        {
            MenuID = 8;
            EmployeeMenu menu = _services.GetEmployeeMenuByID(MenuID);
            ViewBag.Menu = menu.MenuName;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotation quotation = await db.Quotations.FindAsync(id);
            if (quotation == null)
            {
                return HttpNotFound();
            }
            return View(quotation);
        }

        // GET: quotations/Create
        public ActionResult Create()
        {
            MenuID = 9;
            EmployeeMenu menu = _services.GetEmployeeMenuByID(MenuID);
            ViewBag.Menu = menu.MenuName;
            Session["QuotationGuid"] = Guid.NewGuid();
            return View();
        }

        // POST: quotations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "QuotationId,QuotationNo,QuotationDate,QuotationDueDate,BilledByCompanyId,BilledToCustomerId,RefPersonId")] Quotation quotation)
        {
            MenuID = 9;
            EmployeeMenu menu = _services.GetEmployeeMenuByID(MenuID);
            ViewBag.Menu = menu.MenuName;
            if (ModelState.IsValid)
            {
                db.Quotations.Add(quotation);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(quotation);
        }

        // GET: quotations/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Session["QuotationGuid"] = Guid.NewGuid();

            string guid = Session["QuotationGuid"].ToString();

            List<QuotationProducts> quotationProducts = await db.quotationProducts.Where(x => x.QuotationId == id).ToListAsync();

            if (quotationProducts.Count > 0)
            {

                if (!string.IsNullOrWhiteSpace(guid))
                {
                    foreach (QuotationProducts item in quotationProducts)
                    {
                        int productid = item.ProductId;
                        decimal quantity = item.Quantity;
                        tempQuotationProducts tempQuotationCheck = await db.tempQuotationProducts.Where(x => x.Guid == guid && x.productId == productid).FirstOrDefaultAsync();
                        ProductDetails product = await db.productDetails.Where(x => x.Id == productid).FirstOrDefaultAsync();
                        if (tempQuotationCheck == null)
                        {

                            tempQuotationProducts tempQuotation = new tempQuotationProducts()
                            {
                                Guid = guid,
                                productId = item.ProductId,
                                Quantity = item.Quantity,
                                UnitPrice = item.UnitPrice,
                                TotalPrice = item.TotalPrice,
                                QuotationProductId = item.RefId
                            };

                            db.tempQuotationProducts.Add(tempQuotation);
                            await db.SaveChangesAsync();
                        }
                        else
                        {
                            tempQuotationCheck.Quantity = item.Quantity;
                            tempQuotationCheck.UnitPrice = item.UnitPrice;
                            tempQuotationCheck.TotalPrice = item.TotalPrice;
                            db.Entry(tempQuotationCheck).State = EntityState.Modified;
                            await db.SaveChangesAsync();
                        }
                    }

                }
            }

            Quotation quotation = await db.Quotations.FindAsync(id);
            if (quotation == null)
            {
                return HttpNotFound();
            }
            return View(quotation);
        }

        // POST: quotations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "QuotationId,QuotationNo,QuotationDate,QuotationDueDate,BilledByCompanyId,BilledToCustomerId,RefPersonId")] Quotation quotation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quotation).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(quotation);
        }

        // GET: quotations/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotation quotation = await db.Quotations.FindAsync(id);
            if (quotation == null)
            {
                return HttpNotFound();
            }
            return View(quotation);
        }

        // POST: quotations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Quotation quotation = await db.Quotations.FindAsync(id);
            db.Quotations.Remove(quotation);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult _PartialQuotationAdd()
        {
            ViewBag.Companies = db.companyDetails.Where(x => x.IsDeleted == false).ToList();
            return PartialView();
        }

        public ActionResult _PartialQuotationEdit(int id)
        {
            ViewBag.Companies = db.companyDetails.Where(x => x.IsDeleted == false).ToList();
            Quotation quotation = db.Quotations.Find(id);
            return PartialView(quotation);
        }

        public ActionResult _PartialQuotationPreview(int id)
        {
            quotationpreviewModel quotationpreview = new quotationpreviewModel();
            quotationpreview.quotation = db.Quotations.Find(id);
            if (quotationpreview.quotation.BilledByCompanyId != 0)
            {
                quotationpreview.company = db.companyDetails.Where(x => x.CompanyId == quotationpreview.quotation.BilledByCompanyId).FirstOrDefault();
            }
            if (quotationpreview.quotation.BilledToCustomerId != 0)
            {
                quotationpreview.customer = db.customerDetails.Where(x => x.CustomerId == quotationpreview.quotation.BilledToCustomerId).FirstOrDefault();
            }

            if (quotationpreview.quotation.RefPersonId != 0)
            {
                quotationpreview.refPerson = db.customerDetails.Where(x => x.CustomerId == quotationpreview.quotation.RefPersonId).FirstOrDefault();
            }
            quotationpreview.quotationProducts = db.quotationProducts.Where(x => x.QuotationId == quotationpreview.quotation.QuotationId).ToList();
            quotationpreview.productDetails = new List<ProductDetails>();
            foreach (QuotationProducts quoteprod in quotationpreview.quotationProducts)
            {
                List<ProductDetails> productDetails = db.productDetails.Where(x => x.IsDeleted == false && x.Id == quoteprod.ProductId).ToList();
                if (productDetails.Count > 0)
                {
                    quotationpreview.productDetails.AddRange(productDetails);
                }
            }
            quotationpreview.uploads = new List<MultipleFileUpload>();
            foreach (ProductDetails product in quotationpreview.productDetails)
            {

SK_CRM/SK_CRM/Views/quotations/Create.cshtml
@model SK_CRM.Models.Quotation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}

@{
    Html.RenderAction("_PartialQuotationAdd", "quotations");
}

SK_CRM/SK_CRM/Views/quotations/Delete.cshtml
@model SK_CRM.Models.Quotation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}


<div class="content-wrapper container-xxl p-0">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <!-- Horizontal Wizard -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <section class="horizontal-wizard">
                <div class="hide-event-ex">
                    <button type="button" style="display: none;" class="btn btn-outline-primary waves-effect" data-bs-toggle="modal" id="onhidebtn" data-bs-target="#onhide">
                        Confirm
                    </button>
                    <!-- Modal -->
                    <div class="modal fade text-start" id="onhide" tabindex="-1" aria-labelledby="myModalLabel23" aria-hidden="true" style="display: none;">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">

                                <div class="modal-body">
                                    @*<div aria-labelledby="swal2-title" aria-describedby="swal2-html-container" class="swal2-popup swal2-modal swal2-icon-warning swal2-show" tabindex="-1" role="dialog" aria-live="assertive" aria-modal="true" style="display: grid;">

                                        </div>*@
                                    <div class="swal2-icon swal2-warning swal2-icon-show" style="display: flex;">
                                        <div class="swal2-icon-content">!</div>
                                    </div>
                                    <h2 class="swal2-title" id="swal2-title" style="display: block;">Are you sure?</h2>
                                    <div class="swal2-html-container" style="display: block;">You won't be able to revert this!</div>

                                    <div class="swal2-timer-progress-bar-container">
                                        <div class="swal2-timer-progress-bar" style="display: none;"></div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    @*<button type="button" class="btn btn-primary waves-effect waves-float waves-light" data-bs-dismiss="modal">Accept</button>*@
                                    <div class="swal2-actions">
                                        <div class="swal2-loader"></div>
                                        <button type="submit" class="swal2-confirm btn btn-primary" aria-label="" style="display: inline-block;">Yes, delete it!</button>
                                        <button type="button" onclick="quotation.fnBacktoQuotationList();" class="swal2-cancel btn btn-outline-danger ms-1" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </section>
        }
    </div>

</div>

<script type="text/javascript" src="~/assets/js/jquery-3.3.1.min.js"></script>
<script language="javascript" type="text/javascript">
    $(function () {
        $("#onhidebtn").click();
    });
</script>

SK_CRM/SK_CRM/Views/quotations/Details.cshtml
@model SK_CRM.Models.Quotation

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Quotation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuotationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuotationNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuotationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuotationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuotationDueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuotationDueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BilledByCompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BilledByCompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BilledToCustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BilledToCustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefPersonId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefPersonId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.QuotationId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SK_CRM/SK_CRM/Views/quotations/Edit.cshtml
@model SK_CRM.Models.Quotation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}
@{
    Html.RenderAction("_PartialQuotationEdit", "quotations", new { id = Model.QuotationId });
}

SK_CRM/SK_CRM/Views/quotations/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}
@{
    Html.RenderAction("_PartialGetAllQuotations", "PartialView");
}

SK_CRM/SK_CRM/Views/quotations/preview.cshtml
@{
    ViewBag.Title = "preview";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}

@{
    Html.RenderAction("_PartialQuotationPreview", "quotations", new { id = Model.QuotationId });
}