SK_CRM/SK_CRM/Models/AggregateModel/Company/CompanyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SK_CRM.Models.AggregateModel.Company
{
    public class CompanyModel
    {
    }
    public class AllCompanysModel
    {
        public List<company> companies { get; set; }

        public int currentPage { get; set; }
        public int pageSize { get; set; }
        public int totalCount { get; set; }

        public int skipCount { get; set; }
        public int pagefirstNumber { get; set; }
        public int pageLastNumber { get; set; }

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(totalCount, pageSize));

        public bool ShowPrevious => currentPage > 1;
        public bool ShowNext => currentPage < TotalPages;

        public int MinPage => currentPage - 5 > 0 ? currentPage - 5 : 1;

        public int MaxPage => MinPage + 9 < TotalPages ? MinPage + 9 : TotalPages;
    }

}

SK_CRM/SK_CRM/Models/company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SK_CRM.Models
{
    [Table("SK.CompanyDetails", Schema = "dbo")]
    public class company
    {
        [Key]
        public int CompanyId { get; set; }
        [Required]
        [Display(Name = "Code")]
        public string CompanyCode { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string CompanyName { get; set; }
        [Required]
        [Display(Name = "Area and Street")]
        public string Address { get; set; }
        [Required]
        [Display(Name = "Locality")]
        public string Locality { get; set; }
        [Required]
        [Display(Name = "City/Town/District")]
        public string City { get; set; }
        [Required]
        [Display(Name = "Pincode")]
        public string Pincode { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
        public string AltEmail { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Contact Number")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Contact number required")]
        public string ContactNumber { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Alt. Contact Number")]
        public string AltContactNumber { get; set; }
        [Required]
        [Display(Name = "Website")]
        public string Website { get; set; }
        [Display(Name = "TIN No.")]
        public string TINNumber { get; set; }
        [Display(Name = "GST No.")]
        public string GSTINNumber { get; set; }
        [Display(Name = "Quotation Header")]
        public string QuotationHeader { get; set; }
        [Display(Name = "Logo")]
        public string CompanyLogo { get; set; }
        [Display(Name = "Watermark")]
        public string Watermark { get; set; }
        [Display(Name = "GST Detection %")]
        public decimal GSTDetectionPercentage { get; set; }

        [Display(Name = "Created On")]
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        [Display(Name = "Modified Date")]
        public DateTime ModifiedDate { get; set; } = DateTime.Now;

        [Display(Name = "IsDeleted")]
        public bool IsDeleted { get; set; } = false;
    }
}

SK_CRM/SK_CRM/Controllers/companyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SK_CRM.Models;
using SK_CRM.Models.AggregateModel.Company;
using System.Data.SqlClient;
using SK_CRM.Services;

namespace SK_CRM.Controllers
{
    [Authorize]
    public class companyController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private CommonServices _services = new CommonServices();
        private long MenuID;
        // GET: company
        public async Task<ActionResult> Index()
        {
            MenuID = 2;
            EmployeeMenu menu = _services.GetEmployeeMenuByID(MenuID);
            ViewBag.Menu = menu.MenuName;
            return View();
        }

        // GET: company/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            company company = await db.companyDetails.FindAsync(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: company/Create
        public ActionResult Create()
        {
            MenuID = 3;
            EmployeeMenu menu = _services.GetEmployeeMenuByID(MenuID);
            ViewBag.Menu = menu.MenuName;
            Session["CompanyGuid"] = Guid.NewGuid();
            return View();
        }

        // POST: company/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CompanyId,CompanyCode,CompanyName,Address,Email,AltEmail,ContactNumber,AltContactNumber,Website,TINNumber,GSTINNumber,QuotationHeader,CompanyLogo,Watermark,GSTDetectionPercentage,CreatedDate,ModifiedDate,IsDeleted")] company company)
        {
            if (ModelState.IsValid)
            {
                db.companyDetails.Add(company);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: company/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            company company = await db.companyDetails.FindAsync(id);
            Session["CompanyGuid"] = Guid.NewGuid();
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: company/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CompanyId,CompanyCode,CompanyName,Address,Email,AltEmail,ContactNumber,AltContactNumber,Website,TINNumber,GSTINNumber,QuotationHeader,CompanyLogo,Watermark,GSTDetectionPercentage,CreatedDate,ModifiedDate,IsDeleted")] company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: company/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            company company = await db.companyDetails.FindAsync(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: company/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            company company = await db.companyDetails.FindAsync(id);
            db.companyDetails.Remove(company);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]

        public async Task<JsonResult> addCompany(string CompanyName, string Address, string Email, string AltEmail, string ContactNumber, string AltContactNumber,
            string Website, string TINNumber, string GSTINNumber, string QuotationHeader, string GSTDetectionPercentage, string Locality, string City, string Pincode)
        {

            List<tempFileUpload> tempFiles = new List<tempFileUpload>();
            string guid = Session["CompanyGuid"].ToString();
            if (!string.IsNullOrWhiteSpace(guid))
            {
                tempFiles = await db.tempFileUpload.Where(x => x.Guid == guid && x.FormName == "Company").ToListAsync();
            }

            SqlParameter[] prefixParameters = {
                new SqlParameter("@Type", "Company"),
                new SqlParameter("@EventType", "Prefix")
            };
            Address = Address.Replace(Environment.NewLine, "\n");
            company companyDetails = new company()
            {
                CompanyCode = await db.Database.SqlQuery<string>("GetPrefixCode @Type, @EventType", prefixParameters).FirstOrDefaultAsync(),
                CompanyName = CompanyName,
                Address = Address,
                AltContactNumber = AltContactNumber,
                AltEmail = AltEmail,
                CompanyLogo = tempFiles.Where(x => x.Type == "CompanyLogo").Select(x => x.Base64String).FirstOrDefault(),
                ContactNumber = ContactNumber,
                CreatedDate = DateTime.Now,
                Email = Email,
                GSTDetectionPercentage = Convert.ToDecimal(GSTDetectionPercentage),
                GSTINNumber = GSTINNumber,
                ModifiedDate = DateTime.Now,
                QuotationHeader = QuotationHeader,
                TINNumber = TINNumber,
                Watermark = tempFiles.Where(x => x.Type == "Watermark").Select(x => x.Base64String).FirstOrDefault(),
                Website = Website,
                Pincode = Pincode,
                City = City,
                Locality =Locality
                
            };
            db.companyDetails.Add(companyDetails);
            await db.SaveChangesAsync();

            var origins = await db.tempFileUpload.Where(x => x.Guid == guid && x.FormName == "Company").ToListAsync();
            db.tempFileUpload.RemoveRange(origins);
            await db.SaveChangesAsync();

            SqlParameter[] updateParameters = {
                        new SqlParameter("@Type", "Product"),
                        new SqlParameter("@EventType", "Update")
                    };

            string response = await db.Database.SqlQuery<string>("GetPrefixCode @Type, @EventType", updateParameters).FirstOrDefaultAsync();
            if (string.IsNullOrWhiteSpace(response))
            {
                return Json(new { success = false, msg = "GetPrefixCode not updated" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = true, msg = "Successfully added" }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]

        public async Task<JsonResult> updateCompany(int CompanyId, string CompanyName, string Address, string Email, string AltEmail, string ContactNumber, string AltContactNumber,
            string Website, string TINNumber, string GSTINNumber, string QuotationHeader, string GSTDetectionPercentage, string Locality, string City, string Pincode)
        {

            List<tempFileUpload> tempFiles = new List<tempFileUpload>();
            string guid = Session["CompanyGuid"].ToString();
            if (!string.IsNullOrWhiteSpace(guid))
            {
                tempFiles = await db.tempFileUpload.Where(x => x.Guid == guid && x.FormName == "Company").ToListAsync();
            }
            Address = Address.Replace(Environment.NewLine, "\n");
            company companyDetails = await db.companyDetails.FindAsync(CompanyId);

            companyDetails.CompanyName = CompanyName;
            companyDetails.Address = Address;
            companyDetails.AltContactNumber = AltContactNumber;
            companyDetails.AltEmail = AltEmail;

            companyDetails.ContactNumber = ContactNumber;
            companyDetails.Email = Email;
            companyDetails.GSTDetectionPercentage = Convert.ToDecimal(GSTDetectionPercentage);
            companyDetails.GSTINNumber = GSTINNumber;
            companyDetails.ModifiedDate = DateTime.Now;
            companyDetails.QuotationHeader = QuotationHeader;
            companyDetails.TINNumber = TINNumber;
            companyDetails.Locality = Locality;
            companyDetails.Pincode = Pincode;
            companyDetails.City = City;

            string tempCompanyLogo = tempFiles.Where(x => x.Type == "CompanyLogo").Select(x => x.Base64String).FirstOrDefault();
            if (!string.IsNullOrWhiteSpace(tempCompanyLogo))
            {
                companyDetails.CompanyLogo = tempCompanyLogo;              
            }
            string tempwatermark = tempFiles.Where(x => x.Type == "Watermark").Select(x => x.Base64String).FirstOrDefault();
            if (!string.IsNullOrWhiteSpace(tempwatermark))
            {

SK_CRM/SK_CRM/Views/company/Delete.cshtml
@model SK_CRM.Models.company

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}

<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<div class="content-wrapper container-xxl p-0">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <!-- Horizontal Wizard -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <section class="horizontal-wizard">
                <div class="hide-event-ex">
                    <button type="button" style="display: none;" class="btn btn-outline-primary waves-effect" data-bs-toggle="modal" id="onhidebtn" data-bs-target="#onhide">
                        Confirm
                    </button>
                    <!-- Modal -->
                    <div class="modal fade text-start" id="onhide" tabindex="-1" aria-labelledby="myModalLabel23" aria-hidden="true" style="display: none;">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">

                                <div class="modal-body">
                                    @*<div aria-labelledby="swal2-title" aria-describedby="swal2-html-container" class="swal2-popup swal2-modal swal2-icon-warning swal2-show" tabindex="-1" role="dialog" aria-live="assertive" aria-modal="true" style="display: grid;">

                                        </div>*@
                                    <div class="swal2-icon swal2-warning swal2-icon-show" style="display: flex;">
                                        <div class="swal2-icon-content">!</div>
                                    </div>
                                    <h2 class="swal2-title" id="swal2-title" style="display: block;">Are you sure?</h2>
                                    <div class="swal2-html-container" style="display: block;">You won't be able to revert this!</div>

                                    <div class="swal2-timer-progress-bar-container">
                                        <div class="swal2-timer-progress-bar" style="display: none;"></div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    @*<button type="button" class="btn btn-primary waves-effect waves-float waves-light" data-bs-dismiss="modal">Accept</button>*@
                                    <div class="swal2-actions">
                                        <div class="swal2-loader"></div>
                                        <button type="submit" class="swal2-confirm btn btn-primary" aria-label="" style="display: inline-block;">Yes, delete it!</button>
                                        <button type="button" onclick="company.fnBacktoCompanyList();" class="swal2-cancel btn btn-outline-danger ms-1" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </section>
        }
    </div>

</div>

<script type="text/javascript" src="~/assets/js/jquery-3.3.1.min.js"></script>
<script language="javascript" type="text/javascript">
    $(function () {
        $("#onhidebtn").click();
    });
</script>

SK_CRM/SK_CRM/Views/company/Details.cshtml
@model SK_CRM.Models.company

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}

<h2>Details</h2>

<div>
    <h4>company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AltEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AltContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TINNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TINNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GSTINNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GSTINNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuotationHeader)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuotationHeader)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyLogo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyLogo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Watermark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Watermark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GSTDetectionPercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GSTDetectionPercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CompanyId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SK_CRM/SK_CRM/Views/company/Index.cshtml
@{
    ViewBag.Title = "Company";
    Layout = "~/Views/Shared/Layout/_LayoutAdminPanel.cshtml";
}

<div class="content-wrapper container-xxl p-0">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <!-- users list start -->
        <section class="app-user-list">

            <!-- list and filter start -->
            <div class="card">

                <div class="card-datatable table-responsive pt-0">
                    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
                        <div class="d-flex justify-content-between align-items-center header-actions mx-2 row mt-75">
                            <div class="col-sm-12 col-lg-4 d-flex justify-content-center justify-content-lg-start">
                                <div class="dataTables_length" id="DataTables_Table_0_length">
                                    <label>
                                        Show
                                        <select onchange="company.fnCompanyGridPagination(0, 'pagesize', this);" name="DataTables_Table_0_length" aria-controls="DataTables_Table_0" id="ddlPageSize" class="form-select">
                                            <option value="10">10</option>
                                            <option value="25">25</option>
                                            <option value="50">50</option>
                                            <option value="100">100</option>
                                        </select> entries
                                    </label>
                                </div>
                            </div><div class="col-sm-12 col-lg-8 ps-xl-75 ps-0">
                                <div class="dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap">
                                    <div class="me-1">
                                        <div id="DataTables_Table_0_filter" class="dataTables_filter">
                                            <label>Search:<input type="search" class="form-control" placeholder="" aria-controls="DataTables_Table_0" id="txtSearchValue" onkeyup="company.fnCompanyGridPagination(1, 'search', this);"></label>
                                        </div>
                                    </div><div class="dt-buttons d-inline-flex mt-50">
                                        @*<button class="dt-button buttons-collection btn btn-outline-secondary dropdown-toggle me-2" tabindex="0" aria-controls="DataTables_Table_0" type="button" aria-haspopup="true">
                                                <span>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-external-link font-small-4 me-50">
                                                        <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
                                                        <polyline points="15 3 21 3 21 9"></polyline>
                                                        <line x1="10" y1="14" x2="21" y2="3"></line>
                                                    </svg>Export
                                                </span>
                                            </button>*@
                                        <button class="dt-button add-new btn btn-primary" tabindex="0" aria-controls="DataTables_Table_0"
                                                type="button" data-bs-toggle="modal" data-bs-target="#" onclick="location.href='@Url.Action("create", "company")'">
                                            <span>Add New Company</span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="divCompany">
                            @{
                                Html.RenderAction("_PartialGetAllCompanies", "PartialView");
                            }
                        </div>
                    </div>
                </div>

            </div>
            <!-- list and filter end -->
        </section>
        <!-- users list ends -->

    </div>
</div>